# (mesmo conteúdo completo que enviei antes, sem alterações funcionais)
# -- INÍCIO RESUMIDO --
terraform {
  required_version = ">= 1.6.0"
  required_providers {
    aws = { source = "hashicorp/aws", version = "~> 5.53" }
    random = { source = "hashicorp/random", version = "~> 3.6" }
  }
}
provider "aws" { region = var.aws_region }
# ... VPC/Subnets/IGW/RouteTables ...
# ... Security Groups (alb/ec2/rds) ...
# ... RDS postgres ...
# ... IAM role/profile EC2 (SSM + S3 Read) ...
# ... ALB/tg/listener ...
# ... AMI Amazon Linux 2 ...
# ... Launch Template + ASG (user_data carrega app e .env) ...
# ... CloudWatch LogGroup ...
# -- FIM RESUMIDO --
